name: Documentation
description: Report an issue related to documentation.
labels: ["documentation"]

body:
  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of what the issue is.
    validations:
      required: true
